### ISSUE TITLE
Implement rate limits.

### ISSUE THREAD

**Issue by serafettin** [teyit/teyitlink-web#1]

**Comment by gokaygurcan** [comment]
I can pick this up, but before that could you provide some more details please? 

What's the upper limit? When this will expire? Do you have any package in mind? For instance, https://github.com/ded/express-limiter depends on Redis. So, what are the limits here?

Thanks!

**Comment by serafettin** [comment]
Great! 

express-limiter looks well and we can provide a redis instance.  I think 5m window is perfect to minimize storage on redis. 50 snapshots for 5 minutes sounds good.
